      MODULE init_c0
      USE init_c1
      USE init_c3
      USE init_c5
      USE init_c6
      CONTAINS
      SUBROUTINE SSALAC(DOALLOC,NUMCS,CSPOSTSIM,MMNST,SSZ,ERRMES)
      CHARACTER*(*) ERRMES
      CHARACTER*6 SUBNAM
      PARAMETER(SUBNAM='SSALAC')
      INTEGER NUMCS,MMNST,SSZ(MMNST),I
      CHARACTER*(*) CSPOSTSIM(NUMCS)
      LOGICAL :: DOALLOC
      DO I=1,NUMCS
       IF(CSPOSTSIM(I).EQ.'n') THEN
        CALL SSAL1C(DOALLOC,.TRUE.,I,MMNST,SSZ,ERRMES)
        IF(ERRMES(1:1).EQ.'E') GOTO 15000
       END IF
      END DO
      RETURN
15000 CONTINUE
      CALL PERET(SUBNAM)
      RETURN
      END SUBROUTINE SSALAC
      END MODULE init_c0
