      MODULE init_c5
      USE init_c1
      CONTAINS
      SUBROUTINE SSAL1C(DOALLOC,DOINIT,CSNO,MMNST,SSZ,ERRMES)
      CHARACTER*(*) ERRMES
      CHARACTER*10 SUBNAM
      PARAMETER(SUBNAM='SSAL1C')
      INTEGER CSNO,MMNST,SSZ(MMNST),ASTAT,SIZE1
      LOGICAL INCFLG,DOALLOC,DOINIT
      REAL INCFRL
      COMMON /TGINCF/ INCFLG,INCFRL
      CALL TGCVSIZ('cs',CSNO,SIZE1,ERRMES)
      IF(ERRMES(1:1).EQ.'E') GOTO 15000
      ASTAT=0
      IF(CSNO.EQ.1) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00001(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00001=INCFRL
      ELSE IF(CSNO.EQ.2) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00002(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00002=INCFRL
      ELSE IF(CSNO.EQ.3) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00003(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00003=INCFRL
      ELSE IF(CSNO.EQ.4) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00004(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00004=INCFRL
      ELSE IF(CSNO.EQ.5) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00005(SSZ(2),2,SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00005=INCFRL
      ELSE IF(CSNO.EQ.6) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00006(SSZ(2),2,SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00006=INCFRL
      ELSE IF(CSNO.EQ.7) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00007(SSZ(2),2),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00007=INCFRL
      ELSE IF(CSNO.EQ.8) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00008(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00008=INCFRL
      ELSE IF(CSNO.EQ.9) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00009(SSZ(2),2),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00009=INCFRL
      ELSE IF(CSNO.EQ.10) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00010(SSZ(2),2),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00010=INCFRL
      ELSE IF(CSNO.EQ.11) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00011(SSZ(2),2,SSZ(4),SSZ(3)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00011=INCFRL
      ELSE IF(CSNO.EQ.12) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00012(SSZ(2),2,SSZ(4),SSZ(3)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00012=INCFRL
      ELSE IF(CSNO.EQ.13) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00013(SSZ(2),2,SSZ(3)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00013=INCFRL
      ELSE IF(CSNO.EQ.14) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00014(SSZ(2),SSZ(3)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00014=INCFRL
      ELSE IF(CSNO.EQ.15) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00015(SSZ(2),2,SSZ(3)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00015=INCFRL
      ELSE IF(CSNO.EQ.16) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00016(SSZ(2),2,SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00016=INCFRL
      ELSE IF(CSNO.EQ.17) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00017(SSZ(2),2,SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00017=INCFRL
      ELSE IF(CSNO.EQ.18) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00018(SSZ(2),2),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00018=INCFRL
      ELSE IF(CSNO.EQ.19) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00019(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00019=INCFRL
      ELSE IF(CSNO.EQ.20) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00020(SSZ(2),2),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00020=INCFRL
      ELSE IF(CSNO.EQ.21) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00021(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00021=INCFRL
      ELSE IF(CSNO.EQ.22) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00022(SSZ(4),SSZ(5)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00022=INCFRL
      ELSE IF(CSNO.EQ.23) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00023(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00023=INCFRL
      ELSE IF(CSNO.EQ.24) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00024(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00024=INCFRL
      ELSE IF(CSNO.EQ.25) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00025(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00025=INCFRL
      ELSE IF(CSNO.EQ.26) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00026(SSZ(2),SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00026=INCFRL
      ELSE IF(CSNO.EQ.27) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00027(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00027=INCFRL
      ELSE IF(CSNO.EQ.28) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00028(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00028=INCFRL
      ELSE IF(CSNO.EQ.29) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00029(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00029=INCFRL
      ELSE IF(CSNO.EQ.30) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00030(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00030=INCFRL
      ELSE IF(CSNO.EQ.31) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00031(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00031=INCFRL
      ELSE IF(CSNO.EQ.32) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00032(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00032=INCFRL
      ELSE IF(CSNO.EQ.33) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00033(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00033=INCFRL
      ELSE IF(CSNO.EQ.34) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00034(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00034=INCFRL
      ELSE IF(CSNO.EQ.35) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00035(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00035=INCFRL
      ELSE IF(CSNO.EQ.36) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00036(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00036=INCFRL
      ELSE IF(CSNO.EQ.37) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00037(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00037=INCFRL
      ELSE IF(CSNO.EQ.38) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00038(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00038=INCFRL
      ELSE IF(CSNO.EQ.39) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00039(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00039=INCFRL
      ELSE IF(CSNO.EQ.40) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00040(SSZ(4),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00040=INCFRL
      ELSE IF(CSNO.EQ.41) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00041(SSZ(4),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00041=INCFRL
      ELSE IF(CSNO.EQ.42) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00042(SSZ(2),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00042=INCFRL
      ELSE IF(CSNO.EQ.43) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00043(SSZ(2),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00043=INCFRL
      ELSE IF(CSNO.EQ.44) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00044(SSZ(2),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00044=INCFRL
      ELSE IF(CSNO.EQ.45) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00045(SSZ(2),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00045=INCFRL
      ELSE IF(CSNO.EQ.46) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00046(SSZ(4),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00046=INCFRL
      ELSE IF(CSNO.EQ.47) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00047(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00047=INCFRL
      ELSE IF(CSNO.EQ.48) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00048(SSZ(2),2,SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00048=INCFRL
      ELSE IF(CSNO.EQ.49) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00049(SSZ(2),2,SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00049=INCFRL
      ELSE IF(CSNO.EQ.50) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00050(SSZ(2),2),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00050=INCFRL
      ELSE IF(CSNO.EQ.51) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00051(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00051=INCFRL
      ELSE IF(CSNO.EQ.52) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00052(SSZ(2),2),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00052=INCFRL
      ELSE IF(CSNO.EQ.53) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00053(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00053=INCFRL
      ELSE IF(CSNO.EQ.54) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00054(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00054=INCFRL
      ELSE IF(CSNO.EQ.55) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00055(SSZ(2),SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00055=INCFRL
      ELSE IF(CSNO.EQ.56) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00056(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00056=INCFRL
      ELSE IF(CSNO.EQ.57) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00057(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00057=INCFRL
      ELSE IF(CSNO.EQ.58) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00058(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00058=INCFRL
      ELSE IF(CSNO.EQ.59) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00059(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00059=INCFRL
      ELSE IF(CSNO.EQ.60) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00060(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00060=INCFRL
      ELSE IF(CSNO.EQ.61) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00061(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00061=INCFRL
      ELSE IF(CSNO.EQ.62) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00062(SSZ(2),SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00062=INCFRL
      ELSE IF(CSNO.EQ.63) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00063(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00063=INCFRL
      ELSE IF(CSNO.EQ.64) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00064(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00064=INCFRL
      ELSE IF(CSNO.EQ.65) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00065(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00065=INCFRL
      ELSE IF(CSNO.EQ.66) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00066(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00066=INCFRL
      ELSE IF(CSNO.EQ.67) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00067(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00067=INCFRL
      ELSE IF(CSNO.EQ.68) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00068(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00068=INCFRL
      ELSE IF(CSNO.EQ.69) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00069(SSZ(2),2,7),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00069=INCFRL
      ELSE IF(CSNO.EQ.70) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00070(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00070=INCFRL
      ELSE IF(CSNO.EQ.71) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00071(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00071=INCFRL
      ELSE IF(CSNO.EQ.72) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00072(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00072=INCFRL
      ELSE IF(CSNO.EQ.73) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00073(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00073=INCFRL
      ELSE IF(CSNO.EQ.74) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00074(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00074=INCFRL
      ELSE IF(CSNO.EQ.75) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00075(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00075=INCFRL
      ELSE IF(CSNO.EQ.76) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00076(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00076=INCFRL
      ELSE IF(CSNO.EQ.77) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00077(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00077=INCFRL
      ELSE IF(CSNO.EQ.78) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00078(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00078=INCFRL
      ELSE IF(CSNO.EQ.79) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00079(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00079=INCFRL
      ELSE IF(CSNO.EQ.80) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00080(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00080=INCFRL
      ELSE IF(CSNO.EQ.81) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00081(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00081=INCFRL
      ELSE IF(CSNO.EQ.82) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00082(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00082=INCFRL
      ELSE IF(CSNO.EQ.83) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00083(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00083=INCFRL
      ELSE IF(CSNO.EQ.84) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00084(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00084=INCFRL
      ELSE IF(CSNO.EQ.85) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00085(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00085=INCFRL
      ELSE IF(CSNO.EQ.86) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00086(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00086=INCFRL
      ELSE IF(CSNO.EQ.87) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00087(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00087=INCFRL
      ELSE IF(CSNO.EQ.88) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00088(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00088=INCFRL
      ELSE IF(CSNO.EQ.89) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00089(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00089=INCFRL
      ELSE IF(CSNO.EQ.90) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00090(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00090=INCFRL
      ELSE IF(CSNO.EQ.91) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00091(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00091=INCFRL
      ELSE IF(CSNO.EQ.92) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00092(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00092=INCFRL
      ELSE IF(CSNO.EQ.93) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00093(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00093=INCFRL
      ELSE IF(CSNO.EQ.94) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00094(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00094=INCFRL
      ELSE IF(CSNO.EQ.95) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00095(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00095=INCFRL
      ELSE IF(CSNO.EQ.96) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00096(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00096=INCFRL
      ELSE IF(CSNO.EQ.97) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00097(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00097=INCFRL
      ELSE IF(CSNO.EQ.98) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00098(6),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00098=INCFRL
      ELSE IF(CSNO.EQ.99) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00099(4),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00099=INCFRL
      ELSE IF(CSNO.EQ.100) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00100(8),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00100=INCFRL
      ELSE IF(CSNO.EQ.101) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00101(SSZ(4),9),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00101=INCFRL
      ELSE IF(CSNO.EQ.102) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00102(SSZ(2),3,2,6),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00102=INCFRL
      ELSE IF(CSNO.EQ.103) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00103(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00103=INCFRL
      ELSE IF(CSNO.EQ.104) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00104(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00104=INCFRL
      ELSE IF(CSNO.EQ.105) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00105(SSZ(4),3),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00105=INCFRL
      ELSE IF(CSNO.EQ.106) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00106(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00106=INCFRL
      ELSE IF(CSNO.EQ.107) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00107(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00107=INCFRL
      ELSE IF(CSNO.EQ.108) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00108(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00108=INCFRL
      ELSE IF(CSNO.EQ.109) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00109(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00109=INCFRL
      ELSE IF(CSNO.EQ.110) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00110(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00110=INCFRL
      ELSE IF(CSNO.EQ.111) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00111(SSZ(4),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00111=INCFRL
      ELSE IF(CSNO.EQ.112) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00112(SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00112=INCFRL
      ELSE IF(CSNO.EQ.113) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00113(SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00113=INCFRL
      ELSE IF(CSNO.EQ.114) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00114(SSZ(2),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00114=INCFRL
      ELSE IF(CSNO.EQ.115) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00115(SSZ(2),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00115=INCFRL
      ELSE IF(CSNO.EQ.116) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00116(SSZ(2),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00116=INCFRL
      ELSE IF(CSNO.EQ.117) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00117(SSZ(4),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00117=INCFRL
      ELSE IF(CSNO.EQ.118) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00118(SSZ(4),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00118=INCFRL
      ELSE IF(CSNO.EQ.119) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00119(SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00119=INCFRL
      ELSE IF(CSNO.EQ.120) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00120(SSZ(2),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00120=INCFRL
      ELSE IF(CSNO.EQ.121) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00121(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00121=INCFRL
      ELSE IF(CSNO.EQ.122) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00122(SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00122=INCFRL
      ELSE IF(CSNO.EQ.123) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00123(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00123=INCFRL
      ELSE IF(CSNO.EQ.124) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00124(SSZ(2),SSZ(7)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00124=INCFRL
      ELSE IF(CSNO.EQ.125) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00125(SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00125=INCFRL
      ELSE IF(CSNO.EQ.126) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00126(1),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00126=INCFRL
      ELSE IF(CSNO.EQ.127) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00127(SSZ(1),SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00127=INCFRL
      ELSE IF(CSNO.EQ.128) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00128(SSZ(2),2),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00128=INCFRL
      ELSE IF(CSNO.EQ.129) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00129(SSZ(1),SSZ(3)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00129=INCFRL
      ELSE IF(CSNO.EQ.130) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00130(SSZ(3)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00130=INCFRL
      ELSE IF(CSNO.EQ.131) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00131(SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00131=INCFRL
      ELSE IF(CSNO.EQ.132) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00132(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00132=INCFRL
      ELSE IF(CSNO.EQ.133) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00133(SSZ(3)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00133=INCFRL
      ELSE IF(CSNO.EQ.134) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00134(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00134=INCFRL
      ELSE IF(CSNO.EQ.135) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00135(SSZ(1)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00135=INCFRL
      ELSE IF(CSNO.EQ.136) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00136(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00136=INCFRL
      ELSE IF(CSNO.EQ.137) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00137(SSZ(2)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00137=INCFRL
      ELSE IF(CSNO.EQ.138) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00138(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00138=INCFRL
      ELSE IF(CSNO.EQ.139) THEN
        IF(DOALLOC)
     *  ALLOCATE(C00139(SSZ(4)),STAT=ASTAT)
      IF(DOINIT.AND.INCFLG.AND.ASTAT.EQ.0) C00139=INCFRL
      END IF
      IF(ASTAT.NE.0) GOTO 24200
      RETURN
15000 CONTINUE
      CALL PERET(SUBNAM)
      RETURN
15500 CONTINUE
      CALL PERETM(SUBNAM,ERRMES)
      RETURN
24200 CONTINUE
      CALL GPAERR(ASTAT,ERRMES)
      GOTO 15500
      END SUBROUTINE SSAL1C
      END MODULE init_c5
